# Generated by Django 2.2.10 on 2020-04-30 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'category',
                    models.CharField(
                        choices=[('Mobile', (('mobile', 'Mobiles'), ('mob_accessories', 'Mobile Accessories'), ('tablet', 'Tablets'))), ('other', 'Others')], default='Others', max_length=40
                    ),
                ),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('datePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isSold', models.BooleanField(default=False)),
                ('onDiscount', models.BooleanField(default=False)),
                ('discountPercent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('age', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('condition', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
