# Generated by Django 2.2.10 on 2020-05-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(name='category', options={'verbose_name': 'category', 'verbose_name_plural': 'Categories'},),
    ]
