# Generated by Django 2.2.10 on 2020-04-30 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(model_name='post', name='id', field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),),
    ]
