# Generated by Django 2.2.10 on 2020-05-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200504_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discountPercent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
