# Generated by Django 2.2.10 on 2020-05-20 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200510_0222'),
    ]

    operations = [
        migrations.AlterField(model_name='myuser', name='id', field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),),
    ]
