# Generated by Django 2.2.10 on 2020-05-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200508_1437'),
        ('users', '0003_auto_20200508_2028'),
    ]

    operations = [
        migrations.RenameModel(old_name='Wishlist', new_name='SavedPosts',),
    ]
