# Generated by Django 2.2.10 on 2020-05-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20200510_1903"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="posts-images", verbose_name="Image"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.Post",
                    ),
                ),
            ],
        ),
    ]
