# Generated by Django 2.2.10 on 2020-05-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postimages'),
    ]

    operations = [
        migrations.RenameModel(old_name='PostImages', new_name='PostImage',),
        migrations.AlterModelOptions(name='postimage', options={'verbose_name': 'image', 'verbose_name_plural': 'PostImages'},),
    ]
