# Generated by Django 2.2.10 on 2020-06-27 05:28

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200603_1552'),
    ]

    operations = [
        migrations.AlterField(model_name='post', name='description', field=models.TextField(validators=[profanity.validators.validate_is_profane]),),
    ]
