# Generated by Django 2.2.10 on 2020-06-27 05:58

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200627_1058'),
    ]

    operations = [
        migrations.AlterField(model_name='post', name='brand', field=models.CharField(max_length=50, validators=[profanity.validators.validate_is_profane]),),
        migrations.AlterField(model_name='post', name='title', field=models.CharField(max_length=100, validators=[profanity.validators.validate_is_profane]),),
    ]
