# Generated by Django 2.2.10 on 2020-06-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
