# Generated by Django 2.2.10 on 2020-06-28 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0010_post_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="reported_by",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
