# Generated by Django 2.2.10 on 2020-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200604_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedposts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
