# Generated by Django 2.2.10 on 2020-06-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200604_1643'),
    ]

    operations = [
        migrations.RemoveField(model_name='profile', name='hostel',),
        migrations.AddField(model_name='profile', name='hostel', field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Hostel'),),
    ]
