# Generated by Django 2.2.10 on 2020-06-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200605_1915'),
    ]

    operations = [
        migrations.AlterField(model_name='profile', name='hostel', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Hostel'),),
    ]
