# Generated by Django 2.2.10 on 2020-06-27 05:58

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20200609_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
    ]
